### ISSUE TITLE
"Share successful" - define more

### ISSUE THREAD

**Issue by jarofgreen** [WICG/web-share#1]
I may have missed this, but what counts as a "Share successful"?

1) If I click "Share", "Email", write some text, "Discard", does that count?
2) If so, at which point is the successful share message fired?

How about "Failure"?

Has the ramifications of this been thought through for user privacy / control (for want of a better word) - what happens if a website insists you share something before allowing you access to a resource?

**Comment by mgiuca** [comment]
The [interface document](https://github.com/mgiuca/web-share/blob/master/docs/interface.md#navigatorshare) explains this in some more detail. Of relevance here:

> the target app explicitly rejected the share event.

Ultimately it will be up to the target to decide what success or failure means, but my intention (not stated in the current spec) is that the app should accept or reject immediately upon receiving the event. It should not be able to delay fulfilling the promise while the user interacts with it. So in your email case, once the draft is created, the share is successful whether the user discards or not. (Share is intended as a "fire and forget" action, with no long-term relationship between the apps.)

> Has the ramifications of this been thought through for user privacy / control (for want of a better word) - what happens if a website insists you share something before allowing you access to a resource?

On the privacy side, we're mostly concerned that the web app is not able to enumerate the target apps in any way (to avoid leaking information about the user's system), which is why we only provide `canShare` with no additional enumeration capability.

A website could insist you share before allowing access to a resource, but that would likely be a very bad user experience. Websites today can already force you to jump through any hoop they like (sign up to Facebook, pay money, upload a valid passport from Mozambique), and it is up to the website designer to decide which hoops users need to jump through to access content.

**Comment by mgiuca** [comment]
I think my above answer satisfies this request (we do not need to have a stronger definition of "failure").
