### ISSUE TITLE
Document Web Share vs. native share destination capabilities more clearly

### ISSUE THREAD

**Issue by repentsinner** [WICG/web-share#105]
Hi team-

Would it be possible to comment on or document how the [share targets](https://wicg.github.io/web-share/level-2/#dfn-share-target) selection of the Web Share API is currently planned and what a roadmap might be for more native-like coverage?

Currently, if I use the [demo](https://wicg.github.io/web-share/demos/share-files.html) via Chrome 75 on Android 9 to share an image or video file, common 3rd-party targets for these file types (e.g., Instagram, Twitter) don't show up in the share sheet. If I try to share it directly from the (native) Camera app, they do as expected.

The current wording in the spec is:

> Present the user with a choice of one or more share targets, selected **at the user agent's discretion**. The user MUST be given the option to cancel rather than choosing any of the share targets. Wait for the user's choice.

Is the current level of discretion intended to change in future implementations? I realize this question may be better for the Chromium/Chrome team - it's a little unclear to me what is spec and what is implementation at this point.

The Web Share API (and other web app technologies introduced at I/O19) is super promising, but it's unclear how best to understand these differences and the impact they have on 'thin native app' vs. PWA design.

Thanks for considering!

![Screenshot_20190628-172143](https://user-images.githubusercontent.com/4462072/60377539-07388200-99cd-11e9-96d9-398a2ca9cde3.png)
![Screenshot_20190628-172052](https://user-images.githubusercontent.com/4462072/60377540-07388200-99cd-11e9-9f78-a5f0917962b3.png)
![Screenshot_20190628-173342](https://user-images.githubusercontent.com/4462072/60377546-0e5f9000-99cd-11e9-9005-45f305f19138.png)

**Comment by ewilligers** [comment]
If you use Chrome Canary [i.e. the latest nightly build of current Chrome source code], Instagram and Twitter do now show up in the share sheet.

This issue is https://bugs.chromium.org/p/chromium/issues/detail?id=971103

Chrome 75 on Android used [ACTION_SEND_MULTIPLE](https://developer.android.com/reference/android/content/Intent.html#ACTION_SEND_MULTIPLE) even when a single file was being shared, but apps like Instagram and Twitter only accept [ACTION_SEND](https://developer.android.com/reference/android/content/Intent.html#ACTION_SEND), not ACTION_SEND_MULTIPLE.

There is no perfect mapping to each platform's sharing model. e.g. with Chrome Canary's Web Share implementation, there is no way to write an Android app that accepts a text field but not a text file. (Both map to ACTION_SEND text/plain.)

I don't think there are plans to make the spec more prescriptive.

**Comment by repentsinner** [comment]
Thanks for the quick reply @ewilligers!

I was wondering if the difference had to do with the `android.intent.category.BROWSABLE` category, I wouldn't have guessed a multiple vs single files flag.

Confirmed that this works in Canary, can't wait until it lands in stable.
