### ISSUE TITLE
Explainer q: why not a declarative solution?

### ISSUE THREAD

**Issue by marcoscaceres** [WICG/web-share#2]
(Just reading through the docs and filing issues as things come to mind... not fully formed ideas or anything, and probably already have good answers to any questions)

It would be great if the explainer could also discuss pros/cons of a declarative solution. For example: 

```HTML
<img src="https://example.com/cat" sharable>
```

Or:

```HTML
<article sharable> 
</article>
```

And perhaps how the API could be used in conjunction with Web Components?

**Comment by mgiuca** [comment]
We discussed this yesterday. The explainer goes into some detail about the pros and cons of a declarative solution:
https://github.com/WICG/web-share/blob/master/docs/explainer.md#why-not-make-a-share-uri-scheme-like-mailto-instead-of-a-javascript-api

(though that's focused on a URI scheme rather than a "sharable" attribute; we can add some more discussion).

The main advantage of an imperative API is that you can feature detect whether it's supported at all, and you get a promise telling you whether it succeeded.

**Comment by marcoscaceres** [comment]
I think this was addressed, so closing. In any case, the current solution lends itself nicely to a declarative polyfill.
